export interface IExecutionData {
    execPrice: string;
    execQty: string;
    execValue: string;
    leavesQty: string;
    markPrice: string;
    orderId: string;
    orderLinkId: string;
    orderPrice: string;
    orderQty: string;
    orderType: string;
    symbol: string;
    side: string;
    // blockTradeId: string;
    // category: string;
    // execFee: string;
    // execId: string;
    // execTime: string;
    // execType: string;
    // feeRate: string;
    // indexPrice: string;
    // isLeverage: string;
    // isMaker: boolean;
    // markIv: string;
    // stopOrderType: string;
    // tradeIv: string;
    // underlyingPrice: string;
    // closedSize: string;
    // seq: number;
    // createType: string;
}
