export const Events = {
  // Account module
  ACCOUNT_CREATED: 'ACCOUNT.CREATED',
  ACCOUNT_UPDATED: 'ACCOUNT.UPDATED',
  ACCOUNT_DELETED: 'ACCOUNT.DELETED',

  // Balance module
  BALANCES_UPDATED: 'BALANCES.UPDATED',

  // Exchange module
  EXCHANGE_INITIALIZED: 'EXCHANGE.INITIALIZED',
  EXCHANGE_TERMINATED: 'EXCHANGE.TERMINATED',

  // Market module
  MARKETS_UPDATED: 'MARKETS.UPDATED',

  // Order module
  ORDERS_UPDATED: 'ORDERS.UPDATED',
  // CREATE_ORDER: 'ORDER.CREATE',
  // ORDER_CREATED: 'ORDER.CREATED',
  ORDER_UPDATED: 'ORDER.UPDATED',
  // ORDER_TRIGGERED: 'ORDER.TRIGGERED',
  // ORDER_CANCELLED: 'ORDER.CANCELLED',

  // Position module
  POSITIONS_UPDATED: 'POSITIONS.UPDATED',
  // POSITION_CREATED: 'POSITION.CREATED',
  // POSITION_UPDATED: 'POSITION.UPDATED',
  POSITION_CLOSED: 'POSITION.CLOSED',

  // Ticker module
  // TICKERS_UPDATED: 'TICKERS.UPDATED',
  TICKER_PRICE_UPDATED: 'TICKER.PRICE.UPDATED',

  // Core module
  SUBSCRIBE_WEBSOCKET: 'SUBSCRIBE.WEBSOCKET',
  UNSUBSCRIBE_WEBSOCKET: 'UNSUBSCRIBE.WEBSOCKET',
  TICKER_DATA_UPDATED: 'TICKER.DATA.UPDATED',
  EXECUTION_DATA_RECEIVED: 'EXECUTION.DATA.RECEIVED',
  WALLET_DATA_UPDATED: 'WALLET.DATA.UPDATED'
};
