version: "3"
services:
  proxy:
    image: nginx:alpine3.17-slim
    restart: unless-stopped
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf:ro
    ports: [ "0.0.0.0:1234:80" ]
    depends_on:
      - server
      - client
      - adminer
  server:
    build: ./back
    command: npm run start:dev
    volumes:
      - ./back:/app
      # - server-node-modules:/app/node_modules
    ports: [ "0.0.0.0:4000:4000" ]
    environment:
      - NODE_ENV=${NODE_ENV}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
    depends_on:
      - db
  client:
    build: ./front
    command: npm start
    volumes:
      - ./front:/app
      # - client-node-modules:/app/node_modules
    ports: [ "0.0.0.0:3000:3000", "0.0.0.0:35729:35729" ]
    depends_on:
      - server
  db:
    image: postgres:latest
    ports: [ "0.0.0.0:5432:5432" ]
    volumes:
      - db-data:/var/lib/postgresql/data
      # - ./.docker/db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
  adminer:
    image: adminer
    restart: always
    ports: [ "0.0.0.0:5000:8080" ]

volumes:
  db-data:
#   server-node-modules:
#   client-node-modules: 