version: "3.8"
services:
  proxy:
    image: nginx:1.25.4-alpine3.18-slim
    restart: unless-stopped
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "0.0.0.0:1234:80"
    depends_on:
      - server
      - client
      - adminer

  server:
    build: ./back
    command: npm run start:dev
    restart: unless-stopped
    volumes:
      - ./back:/app
      - /app/node_modules
    ports:
      - "0.0.0.0:4000:4000"
    environment:
      NODE_ENV: ${NODE_ENV}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
    depends_on:
      - db

  client:
    build:
      context: ./front
      dockerfile: Dockerfile.dev
    command: npm run start
    restart: unless-stopped
    volumes:
      - ./front:/app
      - /app/node_modules
    ports:
      - "0.0.0.0:3000:3000"
      - "0.0.0.0:35729:35729"
    environment:
      NODE_ENV: development
    depends_on:
      - server

  db:
    image: postgres:16.2-alpine3.19
    restart: unless-stopped
    ports:
      - "0.0.0.0:5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}

  adminer:
    image: adminer:4.8.1-standalone
    restart: unless-stopped
    ports:
      - "0.0.0.0:5000:8080"

volumes:
  db-data: