export enum TriggerType {
  NONE = 'NONE',
  DURATION = 'DURATION',
  TRADINGVIEW = 'TRADINGVIEW',
  CROSSING_UP = 'CROSSING_UP',
  CROSSING_DOWN = 'CROSSING_DOWN',
}

export enum StatusType {
  ACTIVE = 'ACTIVE',
  TRIGGERED = 'TRIGGERED',
  PENDING = 'PENDING',
  PAUSED = 'PAUSED',
  DONE = 'DONE',
}
